2024-11-17 06:24:51,030 [INFO] Loading data...
2024-11-17 06:24:51,069 [INFO] Loaded 1459 keywords and 200 hyperedges
2024-11-17 06:24:51,611 [INFO] Starting training...
2024-11-17 06:24:51,654 [ERROR] An error occurred: The expanded size of the tensor (128) must match the existing size (2) at non-singleton dimension 1.  Target sizes: [2, 128].  Tensor sizes: [2]
Traceback (most recent call last):
  File "main.py", line 144, in main
    train_history = trainer.train(
  File "C:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\trainer.py", line 173, in train
    losses = self.train_epoch(
  File "C:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\trainer.py", line 70, in train_epoch
    losses = self._compute_losses(x, edge_index, pos_pairs, neg_pairs)
  File "C:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\trainer.py", line 91, in _compute_losses
    model_output = self.model(x, edge_index)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\model.py", line 192, in forward
    layer_out, layer_attention = layer(h, edge_index)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "c:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\.venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\K\Desktop\KU_INISW_5th_Group1\HANs\model.py", line 108, in forward
    attention = attention.expand_as(nodes_features)
RuntimeError: The expanded size of the tensor (128) must match the existing size (2) at non-singleton dimension 1.  Target sizes: [2, 128].  Tensor sizes: [2]
